from typing import Dict, Any
import os
import logging
from datetime import datetime

from google import genai

logger = logging.getLogger(__name__)

class WebsiteGeneratorGraph:
    """Simplified website generator using Google Gemini 2.5 Flash"""
    
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        # Configure Gemini client and model instance using new google.genai SDK
        self.client = genai.Client(api_key=self.api_key)

        logger.info("Website generator initialized with Gemini 2.5 Flash")
    
    async def generate_website(self, prompt: str) -> Dict[str, Any]:
        """Generate a complete website from a prompt"""
        logger.info(f"Starting website generation for: {prompt[:100]}...")
        
        try:
            # Create an enhanced prompt for better results
            enhanced_prompt = f"""
Create a complete, modern, and visually stunning HTML website based on this description: "{prompt}"

Requirements:
1. Use modern HTML5 semantic elements
2. Include Tailwind CSS classes for beautiful styling (use CDN)
3. Make it fully responsive for all devices
4. Add smooth animations and hover effects
5. Include proper structure with header, main content, and footer
6. Use modern typography and professional color schemes
7. Add interactive elements where appropriate
8. Include placeholder content that fits the theme
9. Make sure all elements are properly styled and functional
10. Add some JavaScript for basic interactivity

IMPORTANT: Return ONLY the HTML content that goes inside the <body> tag. Do not include <!DOCTYPE html>, <html>, <head>, or <body> tags.

The HTML should be production-ready and look professional with:
- Beautiful design with modern UI/UX principles
- Smooth animations using CSS transitions and JavaScript
- Proper spacing and typography
- Consistent color scheme
- Professional layout structure
- Mobile-first responsive design

Make it visually appealing and interactive!
"""

            logger.info("Sending request to Gemini...")

            # Generate content with Gemini using the new SDK
            response = self.client.models.generate(
                model="gemini-2.5-flash",
                contents=enhanced_prompt,
            )

            # The new SDK returns a response with a text property as well
            if not getattr(response, "text", None):
                raise Exception("No content generated by Gemini")

            generated_code = response.text.strip()
            logger.info(f"Generated code length: {len(generated_code)}")
            
            # Clean up the response
            cleaned_code = self._clean_html_response(generated_code)
            
            logger.info("Website generated successfully")
            
            return {
                "html_code": cleaned_code,
                "metadata": {
                    "generation_timestamp": datetime.now().isoformat(),
                    "model": "gemini-2.5-flash",
                    "original_length": len(generated_code),
                    "cleaned_length": len(cleaned_code)
                },
                "requirements": {"prompt": prompt},
                "errors": []
            }
            
        except Exception as e:
            error_msg = f"Website generation failed: {str(e)}"
            logger.error(error_msg)
            
            # Return a fallback HTML if generation fails
            fallback_html = self._create_fallback_html(prompt)
            
            return {
                "html_code": fallback_html,
                "metadata": {
                    "generation_timestamp": datetime.now().isoformat(),
                    "model": "fallback",
                    "error": error_msg
                },
                "requirements": {"prompt": prompt},
                "errors": [error_msg]
            }
    
    def _clean_html_response(self, html: str) -> str:
        """Clean up HTML response from Gemini"""
        # Remove markdown code blocks
        html = html.replace("```html", "").replace("```", "")
        
        # Remove any full document structure if present
        html = html.replace("<!DOCTYPE html>", "")
        html = html.replace("<html>", "").replace("</html>", "")
        html = html.replace("<body>", "").replace("</body>", "")
        
        # Remove head section if present
        import re
        html = re.sub(r'<head[^>]*>.*?</head>', '', html, flags=re.DOTALL | re.IGNORECASE)
        
        return html.strip()
    
    def _create_fallback_html(self, prompt: str) -> str:
        """Create a fallback HTML when generation fails"""
        return f'''
<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <!-- Navigation -->
    <nav class="bg-white shadow-lg">
        <div class="max-w-7xl mx-auto px-4">
            <div class="flex justify-between h-16">
                <div class="flex items-center">
                    <div class="text-xl font-bold text-gray-800">Generated Website</div>
                </div>
                <div class="hidden md:flex items-center space-x-8">
                    <a href="#home" class="text-gray-600 hover:text-blue-600 transition-colors">Home</a>
                    <a href="#about" class="text-gray-600 hover:text-blue-600 transition-colors">About</a>
                    <a href="#services" class="text-gray-600 hover:text-blue-600 transition-colors">Services</a>
                    <a href="#contact" class="text-gray-600 hover:text-blue-600 transition-colors">Contact</a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section id="home" class="py-20 px-4">
        <div class="max-w-4xl mx-auto text-center">
            <h1 class="text-4xl md:text-6xl font-bold text-gray-800 mb-6">
                Welcome to Your Website
            </h1>
            <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
                This website was generated based on your request: "{prompt}"
            </p>
            <button class="bg-blue-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors">
                Get Started
            </button>
        </div>
    </section>

    <!-- Features Section -->
    <section id="about" class="py-20 px-4 bg-white">
        <div class="max-w-6xl mx-auto">
            <h2 class="text-3xl font-bold text-center text-gray-800 mb-12">Features</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="text-center p-6">
                    <div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg class="w-8 h-8 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <h3 class="text-xl font-semibold mb-2">Modern Design</h3>
                    <p class="text-gray-600">Clean, modern design that looks great on all devices.</p>
                </div>
                <div class="text-center p-6">
                    <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg class="w-8 h-8 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <h3 class="text-xl font-semibold mb-2">Fast Loading</h3>
                    <p class="text-gray-600">Optimized for speed and performance.</p>
                </div>
                <div class="text-center p-6">
                    <div class="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg class="w-8 h-8 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <h3 class="text-xl font-semibold mb-2">Custom Built</h3>
                    <p class="text-gray-600">Generated specifically for your needs using AI.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="py-20 px-4 bg-gray-50">
        <div class="max-w-4xl mx-auto text-center">
            <h2 class="text-3xl font-bold text-gray-800 mb-8">Get in Touch</h2>
            <p class="text-gray-600 mb-8">Ready to get started? Contact us today!</p>
            <form class="max-w-md mx-auto">
                <div class="mb-4">
                    <input type="email" placeholder="Your Email" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                </div>
                <div class="mb-4">
                    <textarea placeholder="Your Message" rows="4" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent"></textarea>
                </div>
                <button type="submit" class="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors">
                    Send Message
                </button>
            </form>
        </div>
    </section>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-8 px-4">
        <div class="max-w-6xl mx-auto text-center">
            <p>&copy; 2025 Generated Website. Created with AI Website Generator.</p>
        </div>
    </footer>
</div>

<script>
// Smooth scrolling for navigation links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {{
    anchor.addEventListener('click', function (e) {{
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {{
            target.scrollIntoView({{
                behavior: 'smooth',
                block: 'start'
            }});
        }}
    }});
}});

// Add fade-in animation on scroll
const observerOptions = {{
    threshold: 0.1,
    rootMargin: '0px 0px -50px 0px'
}};

const observer = new IntersectionObserver((entries) => {{
    entries.forEach(entry => {{
        if (entry.isIntersecting) {{
            entry.target.style.opacity = '1';
            entry.target.style.transform = 'translateY(0)';
        }}
    }});
}}, observerOptions);

// Observe sections for animation
document.querySelectorAll('section').forEach(section => {{
    section.style.opacity = '0';
    section.style.transform = 'translateY(20px)';
    section.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
    observer.observe(section);
}});

// Form handling
document.querySelector('form').addEventListener('submit', function(e) {{
    e.preventDefault();
    alert('Thank you for your message! This is a demo form.');
}});
</script>
'''
